version: '3'

services:
  api.laravel:
    build: .
    environment:
      DB_CONNECTION: "mysql"
      DB_HOST: "10.200.4.161"
      DB_PORT: "3306"
      DB_DATABASE: "PABMI"
      DB_USERNAME: "root"
      DB_PASSWORD: "xQRA0xBC87Gs"
      JWT_SECRET: "2A95F5CCD11DE255FEE9451BDE433"
      JWT_TTL: "60"
      API_DOCUMENTOS: "http://10.200.4.105:8086/api/ApiDoc"
      RUTA_FOLDER_FTP: "/JAGUEDO/"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/public
      - /var/www/html/storage
      - /var/www/html/bootstrap
    ports:
      - 8081:80
    restart: always


